
import { GoogleGenAI, Modality } from "@google/genai";

export const config = {
  runtime: 'edge',
};

export default async function handler(req: Request) {
  if (req.method !== 'POST') return new Response('Method not allowed', { status: 405 });

  try {
    const { text, language } = await req.json();
    
    // Obtain API key strictly from environment variable
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
      return new Response(JSON.stringify({ error: 'API_KEY is not configured.' }), { status: 500 });
    }

    const ai = new GoogleGenAI({ apiKey });
    const speechPrompt = `You are Lord Krishna. Speak the following in a calm, majestic, and spiritual voice with a divine Indian accent: ${text}`;
    
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-preview-tts",
      contents: [{ parts: [{ text: speechPrompt }] }],
      config: {
        responseModalities: [Modality.AUDIO],
        speechConfig: {
          voiceConfig: {
            prebuiltVoiceConfig: { voiceName: 'Kore' },
          },
        },
      },
    });

    const base64Data = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
    if (!base64Data) {
      throw new Error("No audio data generated by the model.");
    }

    return new Response(JSON.stringify({ data: base64Data }), {
      headers: { 'Content-Type': 'application/json' }
    });
  } catch (error: any) {
    console.error("TTS Route Error:", error);
    return new Response(JSON.stringify({ error: error.message || 'Speech generation failed.' }), { 
      status: 500,
      headers: { 'Content-Type': 'application/json' }
    });
  }
}
